name: Notebook Tests

on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

jobs:
  tests:
    name: "Test notebooks"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      - name: "Build"
        run: |
          pip install -r requirements-dev.txt
          pip install . 
      - name: "Run tests"
        run: |
          pytest tests
          python -m pytest --nbmake examples --nbmake-kernel=python --nbmake-timeout=300 --durations=0 -k "not Active_Reset"
        

        
    
        